// Internal State (APP)
export const SET_OPENSIGNDIALOG = 'SET_OPENSIGNDIALOG';
export const SET_OPENSEARCHDIALOG = 'SET_OPENSEARCHDIALOG';
export const SET_USERS = 'SET_USERS';
export const SET_USER = 'SET_USER';

// External State (API)
// API Movies
export const FETCH_API_MOVIE_NOWPLAYING = 'FETCH_API_MOVIE_NOWPLAYING';
export const FETCH_API_MOVIE_POPULAR = 'FETCH_API_MOVIE_POPULAR';
export const FETCH_API_MOVIE_TOPRATED = 'FETCH_API_MOVIE_TOPRATED';
export const FETCH_API_MOVIE_UPCOMING = 'FETCH_API_MOVIE_UPCOMING';
export const FETCH_API_MOVIE_GENRES = 'FETCH_API_MOVIE_GENRES';

// API TV
export const FETCH_API_TV_AIRINGTODAY = 'FETCH_API_TV_AIRINGTODAY';
export const FETCH_API_TV_ONTV = 'FETCH_API_TV_ONTV';
export const FETCH_API_TV_POPULAR = 'FETCH_API_TV_POPULAR';
export const FETCH_API_TV_TOPRATED = 'FETCH_API_TV_TOPRATED';
export const FETCH_API_TV_GENRES = 'FETCH_API_TV_GENRES';

export const FETCH_API_ERROR = 'FETCH_API_ERROR';